node_index: 0
fold_index: ${oc.decode:${oc.env:SLURM_ARRAY_TASK_ID}}
split_dir: /gpfs/gpfs0/ukb_data/fml/british_split
phenotype:
  code: 50
  name: standing_height
  path: ${split_dir}/only_phenotypes/${.name}/node_${node_index}/fold_${fold_index}_train.tsv
  type: real
covariates:
  path: ${split_dir}/covariates/${phenotype.name}/node_${node_index}/fold_${fold_index}_train.tsv
genotype: ${split_dir}/genotypes/split_${node_index}_filtered
output:
  root_dir: ${split_dir}/gwas/${phenotype.name}/node_${node_index}
  path: ${.root_dir}/fold_${fold_index}
threads: 4