node_index: 0
fold_index: 0
split_dir: /gpfs/gpfs0/ukb_data/fml/british_split
phenotype:
  code: 50
  name: standing_height
  path: ${split_dir}/only_phenotypes/${.name}/node_${node_index}/fold_${fold_index}_train.tsv
  type: real
covariates:
  path: ${split_dir}/covariates/${phenotype.name}/node_${node_index}/fold_${fold_index}_train.tsv
genotype:
  train: ${split_dir}/genotypes/split_${node_index}_filtered_train
output:
  path: ${split_dir}/gwas/split${node_index}
threads: 4