split_dir: /gpfs/gpfs0/ukb_data/fml/british_split/
node_count: 5
phenotype:
  name: standing_height
  code: 50
random_state: 1111
# only these covariates will be standardized. 
# change to null if you want standardize every covariate including PCs
zstd_covariates:
  - age