strategy: topk # one of topk, pvalue, mixed
split_dir: /gpfs/gpfs0/ukb_data/fml/british_split
node_count: 4
fold_index: ${oc.decode:${oc.env:SLURM_ARRAY_TASK_ID}}
phenotype:
  name: standing_height
  code: 50
threads: 4
memory_mb: 20000
max_snp_count: 10000 
analysis:
  snp_counts:
   - 1000
   - 2000
   - 5000
   - 10000
  plot_path: ${split_dir}/gwas/${phenotype.name}/node_${node_index}/fold_${fold_index}_snp_selection.png 