# @package _global_

model:
  name: lassonet
  precision: 32
  batch_size: 128
  max_epochs: 92
  hidden_size: 512
  alpha_start: -3
  alpha_end: 0.5
  init_limit: 0.002
  patience: 12
  
experiment:
  gpus: 1 
  optimizer:
    name: sgd
    lr: 1e-2
    weight_decay: 0.0
  scheduler:
    name: exponential_lr
    rounds: ${model.max_epochs}
    epochs_in_round: 1
    gamma: 0.92
