# @package _global_
  
model:
  name: lassonet_classifier
  precision: 32
  batch_size: 16
  max_epochs: 1
  params:
    hidden_size: 256
    alpha_start: -2
    alpha_end: 0.5

experiment:
  pretrain_on_cov: weights