# @package _global_
model:
  name: mlp_classifier
  precision: 32
  max_epochs: 56
  batch_size: 512
  patience: 16

experiment:
  gpus: 1
  optimizer:
    name: sgd
    lr: 1e-2
  scheduler:
    rounds: ${model.max_epochs}
    epochs_in_round: 1
    name: exponential_lr
    gamma: 0.92
