# @package _global_

model:
  name: xgb_classifier
  params:
    max_depth: 4
    alpha: 0.5
    subsample: 0.1084443554670706
    gamma: 3.444210462922724
    eta: 1.0933987257010527
    n_estimators: 300
    colsample_bytree: 0.6027550748438316
    objective: 'multi:softmax'
    min_child_weight: 8
    eval_metric: 'mlogloss' #if metric errors add 'm' to the begging of it's name
  early_stopping_rounds: 30
