# @package _global_

model:
  name: xgb_classifier
  params:
    max_depth: 5
    alpha: 0.5
    subsample: 0.16033994542177357
    gamma: 3.7379856601234502
    eta: 0.9837400040704081
    n_estimators: 1000
    colsample_bytree: 0.6268582588967538
    objective: 'multi:softmax'
    min_child_weight: 8
    eval_metric: 'mlogloss' #if metric errors add 'm' to the begging of it's name
  early_stopping_rounds: 10

