max_epochs: ${scheduler.epochs_in_round}
enable_progress_bar: True
enable_model_summary: False
num_sanity_val_steps: 0
strategy: ddp
devices: ???
accelerator: ???
enable_checkpointing: False
patience: 64
