node_index: 0
split_dir: /gpfs/gpfs0/ukb_data/fml/british_split/

phenotype:
  name: standing_height
  code: 50

data:
  genotype:
    root: ${split_dir}/genotypes/union/split_${node_index}/topk/${phenotype.name}
    train: ${.root}.train_top200
    val: ${.root}.val_top200
  phenotype:
    root: ${split_dir}/only_phenotypes/${phenotype.name}_split_${node_index}
    train: ${.root}_train.tsv
    val: ${.root}_val.tsv
  gwas: ${split_dir}/gwas/split_${node_index}.${phenotype.name}.tsv

model:
  l1: 1e-3
  lr: 1e-3
  epochs: 1
  momentum: 0.9
  batch_size: 512
training:
  gpus:
   - 0
  max_epochs: 1
  enable_progress_bar: False
  enable_model_summary: False
experiment:
  random_state: 1
  description: test mlflow client run
  
