split_dir: /gpfs/gpfs0/ukb_data/fml/ethnic_split
node_index: 0
fold_index: 0
max_snps: 10000

phenotype:
  name: standing_height
  code: 50

data:
  genotype:
    root: ${split_dir}/genotypes/${phenotype.name}/node_${node_index}/no_union/fold_${fold_index}/top_${max_snps}
    train: ${.root}_train
    val: ${.root}_val
    test: ${.root}_test
    
  phenotype:
    root: ${split_dir}/only_phenotypes/${phenotype.name}/node_${node_index}/fold_${fold_index}
    train: ${.root}_train.tsv
    val: ${.root}_val.tsv
    test: ${.root}_test.tsv
    adjusted:
      root: ${split_dir}/only_phenotypes/${phenotype.name}/node_${node_index}/fold_${fold_index}
      train: ${.root}_train.adjusted.tsv
      val: ${.root}_val.adjusted.tsv
      test: ${.root}_test.adjusted.tsv
        
  covariates:
    root: ${split_dir}/covariates/${phenotype.name}/node_${node_index}/fold_${fold_index}
    train: ${.root}_train.tsv
    val: ${.root}_val.tsv
    test: ${.root}_test.tsv
  gwas: ${split_dir}/gwas/${phenotype.name}/node_${node_index}/fold_${fold_index}.tsv

model:
    precision: 16
    batch_size: 1024
    max_epochs: 200
    hidden_size: 32
    alpha_start: -3
    alpha_end: -1
    patience: 10
    
experiment:
    snp_count: 1000
    random_state: 0
    gpus: 1