index: ???
model:
  name: lassonet_regressor
  batch_size: 256
  hidden_size: 64
  alpha_start: -3
  alpha_end: 0.5
  init_limit: 0.001
optimizer:
  name: sgd
  lr: 5e-3
  weight_decay: 0.0
  # momentum: 0.5
scheduler:
  name: exponential_lr
  rounds: ${server.rounds}
  epochs_in_round: 4
  gamma: 0.99
training:
  max_epochs: ${node.scheduler.epochs_in_round}
  enable_progress_bar: False
  enable_model_summary: False
  strategy: ddp