index: ???
model:
  name: mlp_regressor
  batch_size: 256
  l1: 0.0
  hidden_size: 1024
optimizer:
  name: sgd
  lr: 1e-4
  weight_decay: 1e-2
  # momentum: 0.5
scheduler:
  name: exponential_lr
  rounds: ${server.rounds}
  epochs_in_round: 4
  gamma: 0.99
training:
  max_epochs: ${node.scheduler.epochs_in_round}
  enable_progress_bar: False
  enable_model_summary: False
  num_sanity_val_steps: 0
  strategy: ddp
  devices: ???
  accelerator: ???