defaults:
  - model: lassonet_regressor
  - optimizer: sgd
  - scheduler: exponential_lr
  - training: default
  - experiment: gwas 
  - split: region
  - data: topk_snps
  - strategy: fedavg
  - _self_ 

fold:
  index: 0

study: ukb
log_weights: False
log_grad: False

node:
  index: ???
  name: ???

server:
  rounds: 8
  checkpoint_dir: 'models/${data.phenotype.name}/fold_${fold.index}/${model.name}_${experiment.name}'
  port: 8080
  