defaults:
  - _self_
  - data: default
  - experiment: local
  - model: lassonet_regressor
  - optimizer: sgd_ukb
  - scheduler: exponential_lr_ukb
  - training: default

study: ukb
split_dir: /gpfs/gpfs0/ukb_data/test/ac_split
node: 
  index: 0
fold:
  index: 0
