defaults:
  - _self_ 
  - model: lassonet
  - experiment: all_snps

split_dir: /gpfs/gpfs0/ukb_data/test/uneven_split
node_index: 5
gwas_node_index: node_index
fold_index: 0
max_snps: 10000

phenotype:
  name: standing_height
  code: 50

data:
  genotype:
    root: ${split_dir}/genotypes/${phenotype.name}/node_${node_index}/fold_${fold_index}/top_${max_snps}
    train: ${.root}_train
    val: ${.root}_val
    test: ${.root}_test
    
  phenotype:
    root: ${split_dir}/phenotypes/${phenotype.name}/node_${node_index}/fold_${fold_index}
    train: ${.root}_train.tsv
    val: ${.root}_val.tsv
    test: ${.root}_test.tsv
        
  covariates:
    root: ${split_dir}/covariates/${phenotype.name}/node_${node_index}/fold_${fold_index}
    train: ${.root}_train.tsv
    val: ${.root}_val.tsv
    test: ${.root}_test.tsv
  gwas: ${split_dir}/gwas/${phenotype.name}/node_${node_index}/fold_${fold_index}.gwas.tsv

