split_dir: /gpfs/gpfs0/ukb_data/test/uneven_split
node_index: 2
gwas_node_index: node_index
fold_index: 0
max_snps: 10000

phenotype:
  name: standing_height
  code: 50

data:
  genotype:
    root: ${split_dir}/genotypes/${phenotype.name}/node_${node_index}/fold_${fold_index}/top_${max_snps}
    train: ${.root}_train
    val: ${.root}_val
    test: ${.root}_test
    
  phenotype:
    root: ${split_dir}/phenotypes/${phenotype.name}/node_${node_index}/fold_${fold_index}
    train: ${.root}_train.tsv
    val: ${.root}_val.tsv
    test: ${.root}_test.tsv
        
  covariates:
    root: ${split_dir}/covariates/${phenotype.name}/node_${node_index}/fold_${fold_index}
    train: ${.root}_train.tsv
    val: ${.root}_val.tsv
    test: ${.root}_test.tsv
  gwas: ${split_dir}/gwas/${phenotype.name}/node_${node_index}/fold_${fold_index}.gwas.tsv
  

model:
  precision: 16
  batch_size: 1024
  max_epochs: 250
  hidden_size: 100
  alpha: 0.05
  patience: 10
    
experiment:
  model: mlp
  include_genotype: True
  include_covariates: True
  snp_count: 1000
  random_state: 0
  gpus: 1
  
  optimizer:
    name: adamw
    lr: 1e-3
    weight_decay: 1e-3
  scheduler:
    name: one_cycle_lr
    rounds: 160
    epochs_in_round: 4
    div_factor: 25
    final_div_factor: 1e+4