defaults:
  - _self_ 
  - model: lassonet_classifier
  - experiment: asthma

study: ukb
split_dir: /trinity/home/s.mishra/test/ethnic_split
node_index: 0
gwas_node_index: node_index
fold_index: 0

data:
  genotype:
    root: ${split_dir}/genotypes/node_${node_index}/fold_${fold_index}
    train: ${.root}_train
    val: ${.root}_val
    test: ${.root}_test
    
  phenotype:
    name: asthma
    root: ${split_dir}/phenotypes/${data.phenotype.name}/node_${node_index}/fold_${fold_index}
    train: ${.root}_train.tsv
    val: ${.root}_val.tsv
    test: ${.root}_test.tsv
        
  covariates:
    root: ${split_dir}/covariates/${data.phenotype.name}/node_${node_index}/fold_${fold_index}
    train: ${.root}_train.tsv
    val: ${.root}_val.tsv
    test: ${.root}_test.tsv
    
  gwas: ${split_dir}/gwas/${data.phenotype.name}/node_${node_index}/fold_${fold_index}.gwas.tsv

