defaults:
  - _self_
  - model: mlp_classifier
  - experiment: tg

study: tg

phenotype:
  name: ancestry

data:
  x_reduced:
    train: /media/storage/TG/data/chip/external/ukb/tg_pca.sscore

  phenotype:
    name: ancestry
    train: /media/storage/TG/data/chip/external/ukb/tg_pca.tsv

