name: 'diss_0.0'
path: '/mnt/genx-bio-share/TG/data/chip/${.name}'
nodes:
  AMR:
    name: 'Americas'
    resources:
      gpus: 0
    sample_count: 538
    index: AMR
  SAS:
    name: 'South Asia'
    resources:
      gpus: 0
    sample_count: 521
    index: SAS
  EUR:
    name: 'Europe'
    resources:
      gpus: 0
    sample_count: 514
    index: EUR
  EAS:
    name: 'East Asia'
    resources:
      gpus: 0
    sample_count: 532
    index: EAS
  AFR:
    name: 'Africa'
    resources:
      gpus: 0
    sample_count: 519
    index: AFR
