name: 'superpop_split' 
path: '/media/storage/TG/data/chip/${.name}'
nodes: 
  AMR:
    name: 'North America'
    resources:
      gpus: 0
    sample_count: 368
    index: AMR
  SAS:
    name: 'South America'
    resources:
      gpus: 0
    sample_count: 531
    index: SAS
  EUR:
    name: 'Europe'
    resources:
      gpus: 0
    sample_count: 543
    index: EUR
  EAS:
    name: 'East Asia'
    resources:
      gpus: 0
    sample_count: 512
    index: EAS
  AFR:
    name: 'Africa'
    resources:
      gpus: 0
    sample_count: 685
    index: AFR
